// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Franchise.Entities.HuyLT.Models;

public partial class CentralKitchen
{
    public int KitchenId { get; set; }

    public string KitchenName { get; set; }

    public string Address { get; set; }

    public string ContactPerson { get; set; }

    public string PhoneNumber { get; set; }

    public double? Capacity { get; set; }

    public string OperatingStatus { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<ProductionPlan> ProductionPlans { get; set; } = new List<ProductionPlan>();

    public virtual ICollection<StoreOrder> StoreOrders { get; set; } = new List<StoreOrder>();
}