// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Franchise.Entities.HuyLT.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public int StoreId { get; set; }

    public int OrderId { get; set; }

    public int UserAccountId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? FeedbackDate { get; set; }

    public virtual StoreOrder Order { get; set; }

    public virtual FranchiseStore Store { get; set; }
}