// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Franchise.Entities.HuyLT.Models;

public partial class InventoryType
{
    public int TypeId { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }

    public bool IsPerishable { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();
}