// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Franchise.Entities.HuyLT.Models;

public partial class ProductBatch
{
    public int BatchId { get; set; }

    public int PlanId { get; set; }

    public int ProductId { get; set; }

    public DateTime? ProductionDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string Qcstatus { get; set; }

    public double? QuantityProduced { get; set; }

    public virtual ProductionPlan Plan { get; set; }

    public virtual Product Product { get; set; }
}