// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Franchise.Entities.HuyLT.Models;

public partial class RecipeItem
{
    public int RecipeItemId { get; set; }

    public int RecipeId { get; set; }

    public int IngredientId { get; set; }

    public decimal? QuantityRequired { get; set; }

    public string UnitOfMeasure { get; set; }

    public decimal? WastePercentage { get; set; }

    public virtual Recipe Recipe { get; set; }
}