// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Franchise.Entities.HuyLT.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public int ProductTypeId { get; set; }

    public int InventoryId { get; set; }

    public string ProductName { get; set; }

    public string ProductCode { get; set; }

    public decimal? BasePrice { get; set; }

    public decimal? SellingPrice { get; set; }

    public string UnitOfMeasure { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsActive { get; set; }

    public double? Calories { get; set; }

    public int? PreparationTime { get; set; }

    public string ItemCategory { get; set; }

    public int? ShelfLifeDays { get; set; }

    public bool? IsBatchTracked { get; set; }

    public decimal? MinOrderQty { get; set; }

    public int? LeadTimeDays { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual ICollection<ProductBatch> ProductBatches { get; set; } = new List<ProductBatch>();

    public virtual ProductType ProductType { get; set; }

    public virtual ICollection<Recipe> Recipes { get; set; } = new List<Recipe>();

    public virtual ICollection<StoreOrderItem> StoreOrderItems { get; set; } = new List<StoreOrderItem>();
}