// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Franchise.Entities.HuyLT.Models;

public partial class ProductionPlan
{
    public int PlanId { get; set; }

    public int StoreOrderItemId { get; set; }

    public int KitchenId { get; set; }

    public DateOnly PlanDate { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string PlanStatus { get; set; }

    public int? PriorityLevel { get; set; }

    public int? TotalExpectedQuantity { get; set; }

    public int? ActualProducedQuantity { get; set; }

    public string BatchNotes { get; set; }

    public int? LastModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public virtual CentralKitchen Kitchen { get; set; }

    public virtual ICollection<ProductBatch> ProductBatches { get; set; } = new List<ProductBatch>();

    public virtual StoreOrderItem StoreOrderItem { get; set; }
}